LorenzoBettini/javamm

javamm.tests/launches/JvammContentAssistTest.launch, javamm.tests/src/javamm/tests/JavammCompilerTest.xtend, javamm.tests/src/javamm/tests/JavammValidatorTest.xtend, javamm.tests/src/javamm/ui/tests/JavammContentAssistTest.xtend, javamm.ui/src/javamm/ui/contentassist/JavammAbstractXbaseProposalProvider.java, javamm/src/javamm/Javamm.xtext, javamm/src/javamm/compiler/JavammXbaseCompiler.java, javamm/src/javamm/util/JavammModelUtil.xtend
=> Iterable for

javamm.tests/src/javamm/tests/JavammCompilerTest.xtend, javamm.tests/src/javamm/tests/JavammValidatorTest.xtend, javamm/src/javamm/javamm/impl/JavammAdditionalXVariableDeclarationImplCustom.java
Otherwise assignment to final variable is not checked on additional
variable declarations.
Closes #2
=> additional variable declaration isWritable delegated to container

javamm.tests/src/javamm/tests/JavammAbstractTest.xtend, javamm.tests/src/javamm/tests/JavammCompilerTest.xtend, javamm.tests/src/javamm/tests/JavammFormatterTest.xtend, javamm.tests/src/javamm/tests/JavammParserTest.xtend, javamm.tests/src/javamm/tests/JavammValidatorTest.xtend, javamm/src/javamm/formatting2/JavammFormatter.xtend, javamm/src/javamm/typesystem/JavammTypeComputer.xtend
=> Task 16 implement instanceof

javamm.releng/pom.xml, javamm/pom.xml
Change-Id: I6050c20d3adae750db2f4c1d2518fc6ce0437821
=> switched to fornax plugin

javamm.tests/src/javamm/tests/JavammCompilerTest.xtend, javamm.tests/src/javamm/tests/JavammValidatorTest.xtend, javamm/model/custom/Javamm.ecore, javamm/src/javamm/Javamm.xtext, javamm/src/javamm/jvmmodel/JavammJvmModelInferrer.xtend, javamm/src/javamm/validation/JavammValidator.xtend
=> Task 21 vararg parameters

javamm.tests/src/javamm/tests/JavammCompilerTest.xtend, javamm/src/javamm/typesystem/PatchedTypeComputer.java
A temporary patch for #34 
Closes #34
=> Task 34 problems in binary ope

javamm.tests/src/javamm/tests/JavammValidatorTest.xtend, javamm/src/javamm/JavammRuntimeModule.java, javamm/src/javamm/controlflow/JavammSureReturnComputer.xtend, javamm/src/javamm/util/JavammModelUtil.xtend, javamm/src/javamm/validation/JavammImplicitReturnFinder.java, javamm/src/javamm/validation/JavammValidator.xtend
=> Task 32 missing return

javamm.tests/src/javamm/tests/JavammCompilerTest.xtend, javamm.tests/src/javamm/tests/JavammValidatorTest.xtend, javamm/src/javamm/util/JavammModelUtil.xtend, javamm/src/javamm/validation/JavammValidator.xtend
=> Task 50 method overloading

before_script.sh, javamm.tests/src/javamm/tests/JavammCompilerTest.xtend, javamm.tests/src/javamm/tests/JavammExpressionHelperTest.xtend, javamm.tests/src/javamm/tests/JavammTypeComputerTest.xtend, javamm.tests/src/javamm/tests/JavammValidatorTest.xtend, javamm/src/javamm/compiler/JavammXbaseCompiler.java, javamm/src/javamm/typesystem/PatchedTypeComputer.java, javamm/src/javamm/util/JavammExpressionHelper.xtend
=> Task 53 byte short and negativ

javamm.tests/src/javamm/tests/JavammValidatorTest.xtend, javamm/src/javamm/validation/JavammValidator.xtend
=> Task 56 final array

javamm.tests/src/javamm/tests/JavammCompilerTest.xtend, javamm/src/javamm/compiler/JavammXbaseCompiler.java, javamm/src/javamm/compiler/PatchedXbaseCompiler.java
=> Task 58 conditional expression

javamm.tests/src/javamm/tests/JavammBranchingStatementDetectorTest.xtend, javamm.tests/src/javamm/tests/JavammBreakStatementDetectorTest.xtend, javamm.tests/src/javamm/tests/JavammCompilerTest.xtend, javamm.tests/src/javamm/tests/JavammValidatorTest.xtend, javamm/src/javamm/controlflow/JavammBranchingStatementDetector.xtend, javamm/src/javamm/controlflow/JavammBreakStatementDetector.xtend, javamm/src/javamm/controlflow/JavammEarlyExitComputer.xtend
=> Task 59 loops with true condit

javamm.releng/pom.xml, javamm.targetplatform/mars-xtext-2.10.target, javamm.tests/src/javamm/tests/JavammFormatterTest.xtend, javamm.tests/src/javamm/tests/JavammValidatorTest.xtend, javamm.workspace/Javamm.setup, javamm/META-INF/MANIFEST.MF, javamm/src/javamm/formatting2/JavammFormatter.xtend
=> Task 74 use jbase 030

javamm.examples/src-gen/javamm/OperatorsBoolean.java, javamm.examples/src/javamm/OperatorsBoolean.javamm, javamm.releng/pom.xml, javamm.requirements.feature/feature.xml, javamm.runtime/META-INF/MANIFEST.MF, javamm.targetplatform/mars-xtext-2.10.target, javamm.tests/src/javamm/tests/JavammAbstractTest.xtend, javamm.tests/src/javamm/tests/JavammCompilerTest.xtend, javamm.tests/src/javamm/tests/JavammParsingTest.xtend, javamm.tests/src/javamm/tests/JavammSerializerTest.xtend, javamm.tests/src/javamm/tests/JavammValidatorTest.xtend, javamm.workspace/Javamm.setup, javamm/META-INF/MANIFEST.MF
=> Task 40 non lazy boolean opera

javamm.releng/pom.xml, javamm.runtime/META-INF/MANIFEST.MF, javamm.targetplatform/mars-xtext-2.10.target, javamm.workspace/Javamm.setup, javamm/META-INF/MANIFEST.MF
Closes #79 
Task-Url: https://github.com/LorenzoBettini/javamm/issues/79
=> 79: dep on Jbase 0.5.0

.travis.yml, javamm.releng/pom.xml, javamm.sdk/feature.xml, javamm.swtbot.tests/META-INF/MANIFEST.MF, javamm.swtbot.tests/src/javamm/swtbot/tests/AbstractJavammSwtbotTest.java, javamm.swtbot.tests/src/javamm/swtbot/tests/JavammSwtBotTest.java, javamm.targetplatform/neon-xtext-2.12.target, javamm.tests/src/javamm/tests/JavammValidatorTest.xtend, javamm.ui.tests/META-INF/MANIFEST.MF, javamm.ui.tests/src/javamm/tests/utils/ui/PluginProjectHelper.xtend, javamm.ui.tests/src/javamm/ui/tests/JavammAbstractWizardTest.xtend, javamm.ui.tests/src/javamm/ui/tests/JavammContentAssistTest.xtend, javamm.ui.tests/src/javamm/ui/tests/JavammNewFileWizardTest.xtend, javamm.ui.tests/src/javamm/ui/tests/JavammNewProjectWizardTest.xtend, javamm.ui.tests/src/javamm/ui/tests/JavammNewSelfAssessmentProjectWizardTest.xtend, javamm.ui.tests/src/javamm/ui/tests/JavammOutlineTest.xtend, javamm.ui.tests/src/javamm/ui/tests/JavammSelfAssessmentBuilderTest.xtend, javamm.ui.tests/src/javamm/ui/tests/JavammWorkbenchTest.xtend, javamm.workspace/Javamm.setup, javamm/META-INF/MANIFEST.MF
=> Task 91 port to xtext 2.12

.github/workflows/maven.yml, .github/workflows/windows-mac.yml, javamm.examples/pom.xml, javamm.parent/pom.xml, javamm.site/javamm.eclipse.ide.product, javamm.site/pom.xml, javamm.targetplatform/javamm.target.target, javamm.tests/META-INF/MANIFEST.MF, javamm.ui.examples/META-INF/MANIFEST.MF, javamm.ui.examples/pom.xml, javamm.ui.tests/META-INF/MANIFEST.MF, javamm.ui.tests/pom.xml, javamm.ui/META-INF/MANIFEST.MF, javamm.ui/plugin.xml, javamm.ui/plugin.xml_gen, javamm.workspace/Javamm.setup, javamm/META-INF/MANIFEST.MF, javamm/plugin.xml, javamm/plugin.xml_gen
=> Task 113 port to xtext 2.25

.github/workflows/maven.yml, javamm.eclipse.sdk/pom.xml, javamm.examples/pom.xml, javamm.parent/launches/javamm.parent Jacoco Report.launch, javamm.parent/launches/javamm.parent Sonarqube.launch, javamm.parent/pom.xml, javamm.runtime/pom.xml, javamm.site/pom.xml, javamm.swtbot.tests/pom.xml, javamm.targetplatform/pom.xml, javamm.tests.parent/pom.xml, javamm.tests.report/pom.xml, javamm.tests/pom.xml, javamm.ui.tests/pom.xml, javamm.ui.tests/ui-tests.txt, javamm.ui/pom.xml, javamm/pom.xml
Task-Url: https://github.com/LorenzoBettini/javamm/issues/116
Closes #116
=> 116: Use Xtext build utils

javamm.parent/pom.xml, javamm.requirements.feature/feature.xml, javamm.site/category.xml, javamm.site/pom.xml, javamm.site/replace-references-in-category.launch, javamm.site/templates/category.xml
=> Task 117 deploy p2 repo with site references

javamm.parent/pom.xml, javamm.requirements.feature/feature.xml, javamm.site/category.xml, javamm.targetplatform/javamm.target.target, javamm.workspace/Javamm.setup, javamm/META-INF/MANIFEST.MF, javamm/build.properties, javamm/pom.xml
=> Task 123 update to jbase 0.12

.github/workflows/maven.yml, javamm.parent/pom.xml, javamm.requirements.feature/feature.xml
=> Task 125 updated to jbase 0.12.1

.github/workflows/maven.yml, .github/workflows/windows-mac.yml, javamm.parent/pom.xml, javamm.site/category.xml, javamm.swtbot.tests/src/javamm/swtbot/tests/AbstractJavammSwtbotTest.java, javamm.targetplatform/javamm.target.target, javamm.workspace/Javamm.setup
=> Task 128 update to 2021 09

javamm.parent/pom.xml, javamm.site/category.xml, javamm.targetplatform/javamm.target.target, javamm.workspace/Javamm.setup
=> Task 135 build with 2021 12

javamm.parent/pom.xml
Task-Url: https://github.com/LorenzoBettini/javamm/issues/138
Closes #138
=> 138: Build also with aarch64

javamm.parent/pom.xml
Task-Url: https://github.com/LorenzoBettini/javamm/issues/137
Closes #137
=> 137: Update to xtext-build-utils 0.6.7

javamm.examples/pom.xml, javamm.parent/pom.xml, javamm.requirements.feature/feature.xml, javamm.targetplatform/javamm.target.target, javamm.workspace/Javamm.setup, javamm/META-INF/MANIFEST.MF
Task-Url: https://github.com/LorenzoBettini/javamm/issues/136
Closes #136
=> 136: Use the new Jbase 1.0
